export const LANDING_CODE_LINES = [
  '//@version=5',
  'indicator("Momentum Breakout", overlay=true)',
  '',
  'var float balance = input.float(15000, "Account $")',
  'var float riskPct  = input.float(1.0, "Risk %")',
  '',
  '// ── 3-Tier Alerts ──────────────────────',
  'bullAvg = rsiClose > 60 and close > ema21',
  'bullStr = bullAvg and volume > volAvg*1.5',
  '',
  'alertcondition(bullAvg, "Average Signal")',
  'alertcondition(bullStr, "Strong Signal")',
  '',
  '// ── Auto SL / TP ───────────────────────',
  'sl = ta.lowest(low, 10)',
  'tp = close + (close - sl) * 2',
  'plot(sl, "Stop Loss", color.red, linewidth=2)',
  'plot(tp, "Take Profit", color.green, linewidth=2)',
];
